Nominate Stefan Karschti as MapLibre Voting Member
maplibre/maplibre pull request #379
Opened 2024-07-22 09:57 UTC by louwers

I would like to nominate @stefankarschti to become a MapLibre Voting Member.

## Motivation

Stefan has been instrumental in implementing the Metal backend for MapLibre Native.

## Checklist

- [ ] The nominee contributed in a non-trivial way or donated funds to the MapLibre Organization.
- [ ] This PR updates `VOTING_MEMBERS.md` with the GitHub handle and current employer (when applicable) of the nominee.
- [ ] The nominee has approved the pull request to indicate they want to be a Voting Member of MapLibre.
- [ ] The nominee has shared their full name and contact e-mail with [this form](https://share-eu1.hsforms.com/1OcrNFreTRMqPRb0_PlOt3gfn2ab).
- [ ] At the voting deadline[^1], more [Voting Members](https://github.com/maplibre/maplibre/blob/main/VOTING_MEMBERS.md) have approved this pull request than disapproved this pull request.

More details on the process of nominating Voting Members can be found [here](https://github.com/maplibre/maplibre/issues/376).

[^1]: Thursday, Aug 22nd, 2024 at 17:00 CEST

2024-07-22 15:44 UTC, wipfli approved these changes

2024-07-22 15:51 UTC, mojodna approved these changes

2024-08-05 12:44 UTC, birkskyum approved these changes

2024-08-05 12:44 UTC, birkskyum requested changes
Why listed twice?

2024-08-07 15:25 UTC, closed without merging

2024-08-07 15:26 UTC, louwers commented
Oops.